### ISSUE TITLE
Use parser in https://github.com/Gk0Wk/TW5-CodeMirror-Enhanced

### ISSUE THREAD

**Issue by linonetwo** [SmilyOrg/tw5-monaco#1]
It has a tw syntax highlighter.

And can you provide [[ complete and / menu like it?

**Comment by linonetwo** [comment]
Do you think monaco can make WYSIWYG  editor like [https://github.com/laobubu/HyperMD](https://github.com/laobubu/HyperMD) ?

**Comment by SmilyOrg** [comment]
Hey, that looks pretty cool, I'd have to check out how it handles syntax highlighting.

> It has a tw syntax highlighter.

Check out the [latest version](https://smilyorg.github.io/tw5-monaco/), I've added something like that.

> And can you provide [[ complete and / menu like it?

Yes, that's definitely possible and I'm looking into it.

> Do you think monaco can make WYSIWYG  editor like https://github.com/laobubu/HyperMD ?

Cool editor! I'm not sure actually, I googled a bit and it doesn't seem like you can really _hide_ characters. Monaco was really made for editing code specifically, so WYSIWYG possibilities are limited.

The compromise I made in the highlighting was to just to fade the characters into the background more so they don't stand out as much.

There are lots of ways to _add_ things to the text though, so that might be interesting in a different way. See [Monaco playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example).

For more WYSIWYG style editing, I played around with [Editor.js](https://editorjs.io/) as part of another plugin, but it's a lot trickier, so I didn't get that far.

**Comment by linonetwo** [comment]
I'm creating [https://github.com/tiddly-gittly/slate-write](https://github.com/tiddly-gittly/slate-write) as a view-template editor.

I think I will use monaco in edit mode, and react-slate in view mode in the future.
